export default function Terms() {
    return (
      <div className="terms-container">
        <h1>TERMS OF USE</h1>
        <pre className="terms-text">
  {`Last updated October 14, 2024.

These Terms of Use (“Agreement”) of LXQ Inc., a Delaware corporation (“Company” or “us” or “we”), govern your use of our website located at www.lxq.ai (the “Website”). By accessing or using the Website, you expressly accept all of the provisions of this Agreement and represent to us that you are at least 18 years of age and are legally competent to enter into and agree to this Agreement. If you do not accept this Agreement, then you are not authorized to use the Website.This agreement includes: (1) an arbitration provision; (2) a waiver of rights to bring a class action against us; and (3) a release by you of all claims for damage against us that may arise out of your use of the website. If you agree to these terms on behalf of a legal entity: (a) you represent and warrant that you have the authority to bind that entity and any representatives it allows to access the website; (b) such entity is responsible for any breach of this agreement by any of its representatives; and (c) “you” and “your” as used herein will refer and apply to that entity and the persons that access the website on its behalf.

1. THE WEBSITE

1.1 Eligibility. Registering for an account or using the Website is only available to persons who are at least eighteen (18) years old and are otherwise capable of forming legally binding contracts under applicable law. In order to create an account, we may request your name and contact information.

1.2 Your Account. We reserve the right to validate your identity and account information at any time. You are responsible for ensuring and maintaining the secrecy and security of your account password, and are responsible for any activities that occur on the Website under your account. You must notify the Company support immediately if you suspect that your password has been lost or stolen.

1.3 Termination. You may cancel your account and terminate this Agreement at any time upon notice to Company. This Agreement and your right to access and use the Website will automatically terminate upon any violation by you of any term or condition of this Agreement. Sections 1.3, 2.3, 3.2, 5, 6, and 7 will survive any termination of this Agreement.

1.4 Alerts and Notifications. As part of your use of the Website, you may receive notifications, text messages, alerts, or emails. You agree to the receipt of these communications. You can control receipt of non-service related communications by contacting us. You are responsible for any messaging or data fees you may be charged by your wireless carrier.

1.5 Privacy. We respect your privacy. For information regarding what information we collect from you and how we use and share it, please see our Privacy Policy.

LICENSE AND USE

2.1 Website. Subject to your compliance with the terms and conditions of this Agreement, Company hereby grants you a personal, non-exclusive, non-transferable, revocable, limited license (without the right to sublicense) to access and use the Website for your personal non-commercial use only, and subject to the limitations set forth below. This Agreement is limited to the intellectual property rights of Company and its licensors and does not include any rights to other intellectual property. We reserve any and all rights not expressly granted to you pursuant to this Agreement.

2.2 Use Restrictions

A. Except as specifically permitted herein, you agree that you will not directly or indirectly: (i) distribute, sell, assign, encumber, transfer, rent, lease, loan, sublicense, modify, time-share or otherwise exploit the Website in any unauthorized manner; (ii) use the Website in any service bureau arrangement; (iii) copy, reproduce, adapt, create derivative works of, translate, localize, port or otherwise modify the Website or any part thereof in any form or manner or by any means; (iv) harvest or scrape any content or data from the Website; (v) remove or alter any copyright or other proprietary rights' notice or restrictive rights legend contained or included in the Website; (vi) decompile, disassemble, reverse compile, reverse assemble, reverse translate or otherwise reverse engineer any part of the Website (except as and only to the extent any foregoing restriction is prohibited by applicable law); (vii) use any means to discover the source code of any portion of the Website; (viii) otherwise circumvent any functionality that controls access to or otherwise protects the Website; or (ix) permit any third party to engage in any of the foregoing.

B. Further, you agree that: (a) you will not use the Website if you are not fully able and legally competent to agree to this Agreement; (b) you will only use the Website in full compliance with the laws and regulations of the state in which you use the Website and all applicable federal laws; (c) you will not use the Website for sending or storing any material prohibited by the Law or for fraudulent purposes or to engage in any offensive, indecent or objectionable conduct; and (d) you will keep secure and confidential your account password or any identification we provide you which allows you to use the Website.

2.3 Ownership. The Website and its content, including its “look and feel” (e.g., text, graphics, images, logos), proprietary content, information and other materials, are protected under intellectual property, copyright, trademark and other laws. You acknowledge and agree that Company and/or our licensors own all right, title and interest in and to the Website (including without limitation any and all patent, copyright, trade secret, trademark, show-how, know-how and any and all other intellectual property rights therein or related thereto) and you agree not to take any action(s) inconsistent with such ownership interests. You do not acquire any rights or licenses under any of Company's (or its licensors') patents, patent applications, copyrights, trade secrets, trademarks or other intellectual property rights on account of this Agreement. Any and all: (a) suggestions for correction, change and modification to the Website and other feedback (including but not limited to quotations of written or oral feedback), information and reports your provide to Company (collectively “Feedback”); and all (b) improvements, updates, modifications or enhancements, whether made, created or developed by Company or otherwise relating to the Website (collectively, “Revisions”), are and will remain the property of Company. You acknowledge and expressly agree that any contribution of Feedback or Revisions does not and will not give or grant you any right, title or interest in the Website or in any such Feedback or Revisions. All Feedback and Revisions become the sole and exclusive property of Company and Company may use and disclose Feedback and/or Revisions in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim. You hereby assign to Company any and all right, title and interest (including, but not limited to, any patent, copyright, trade secret, trademark, show-how, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback and Revisions. At Company's request, you will execute any document, registration or filing required to give effect to the foregoing assignment.

2.4 Changes. We reserve the right to do any of the following at any time and will not be liable to you or any third party for so doing: (a) change the Website, including terminating, eliminating, supplementing, modifying, adding to or discontinuing any content, functionality, promotion, data on or feature of the Website or the hours during which the Website is available, or (b) implement new fees or charges or change any existing fees or charges in connection with the use of the Website.

2.5 Our Enforcement Rights. We are not obligated to monitor access or use of the Website, but we have the right to do so for the purpose of operating the Website, to ensure compliance with this Agreement, and to comply with applicable law or other legal requirements. We may consult with and disclose unlawful conduct to law enforcement authorities; and pursuant to valid legal process, we may cooperate with law enforcement authorities to prosecute users who violate the law.

2.6 Third Party Services and Materials. The Website may display, include or make available content, data, information, applications or materials from third parties (“Third Party Materials”) or provide links to certain third party web sites. By using the Website, you acknowledge and agree that we are not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third Party Materials or web sites. We do not warrant or endorse and do not assume and will not have any liability or responsibility to you or any other person for any third-party services, Third Party Materials or web sites, or for any other materials, products, or services of third parties. Third Party Materials and links to other web sites are provided solely as a convenience to you.

3. CONTENT POLICY

3.1 Your Content. You represent and warrant that you own or have a valid license to all content or other materials you upload, post, publish or display through the Website (collectively, “Content”). You hereby grant the Company and its affiliates a worldwide, non-exclusive, royalty free, fully paid, transferable, sub-licensable, perpetual, and irrevocable license to copy, modify, display, perform, distribute, create derivative works of and otherwise use your Content in connection with the operation and promotion of the Website, though subject to our Privacy Policy.

3.2 Disclosure of Your Content. You acknowledge and agree that the Company may preserve and/or disclose your Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce these Terms; (c) respond to claims that any of your Content violates the rights of third parties; or (d) protect the rights, property, or personal safety of the Company, its affiliates, officers, employees, representatives and agents, as well as Website users and the general public.

3.3 Prohibited Content. You are solely responsible for all of your Content, and agree not to upload any Content prohibited by applicable law or the restrictions in this Section. The Company reserves the right to investigate and take appropriate legal action against any account holders who violate this Section. Specifically, you represent and warrant that none of your Content: (a) infringes any intellectual property, proprietary, contractual or privacy rights of any party; (b) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (c) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail”, “spam”, “chain letters”, “pyramid schemes”, “contests”, “sweepstakes”, or any other form of solicitation; (d) is unlawful, harmful, threatening, abusive, harassing, tortious, violent, defamatory, vulgar, obscene, pornographic, libelous, or otherwise objectionable; or (e) in the sole judgment of the Company, is objectionable or which may expose the Company or its users to any harm or liability of any kind.

4. DIGITAL MILLENIUM COPYRIGHT ACT

4.1 Anyone who believes that his or her work has been reproduced on the Website in a manner which constitutes copyright infringement may submit a notification to our copyright agent in accordance with the Digital Millennium Copyright Act (the “DMCA”), by providing the following information in writing: (a) identification of the copyrighted work that is claimed to be infringed; (b) identification of the allegedly infringing material that is requested to be removed, including a description of where it is located on the Website; (c) information for our copyright agent to contact you, such as an address, telephone number, and, if available, e-mail address; (d) a statement that you have a good faith belief that the identified, allegedly infringing use is not authorized by the copyright owners, its agent or the law; (e) a statement that the information above is accurate, and under penalty of perjury, that you are the copyright owner or the authorized person to act on behalf of the copyright owner; and (f) a physical or electronic signature of a person authorized to act on behalf of the owner of the copyright or of an exclusive right that is allegedly infringed. If you are asserting infringement of an intellectual property right other than copyright, please specify the intellectual property right at issue (for example, “trademark”) by notating this in your written notice. You acknowledge that if you fail to comply with all of the requirements for a notice of infringement as specified above, your DMCA notice may not be valid.

4.2 Notices of copyright infringement claims should be sent by mail to LXQ Inc., 8 The Green #19090, Dover, DE, 19901, United States; or by email to contact@lxq.ai. We will respond expeditiously to claims of copyright infringement that are reported to our copyright agent in the notification explained above. It is our policy, in appropriate circumstances and at its discretion, to disable or terminate the accounts of users who repeatedly infringe copyrights or intellectual property rights of others.

4.3 If you believe that any of your Content that was removed (or to which access was disabled) after we received a notice of copyright infringement is not actually infringing, or that you have the authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use such content, you may send a counter-notice containing the following information to our copyright agent: (a) your physical or electronic signature (with your full legal name); (b) identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled; (c) a statement that you have a good faith belief, under penalty of perjury, that the content was removed or disabled as a result of mistake or a misidentification of the content; and (d) your name, address, telephone number, and email address, and a statement that you will accept service of process from the person who provided the original notification of the alleged infringement.

4.4 If a counter-notice is received by our copyright agent, we may send a copy of the counter-notice to the original complaining party informing that person that we may replace the removed content or cease disabling it. Unless the original complaining party files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in ten (10) business days or more after receipt of the counter-notice, at our sole discretion. Please understand that filing a counter-notification may lead to legal proceedings between you and the complaining party to determine ownership. Be aware that there may be adverse legal consequences in your country if you make a false or bad faith allegation by using this process.

4.5 Further information on the DMCA can be found in 17 U.S.C. 512 or on the United States Copyright Office website at http://www.copyright.gov/legislation/dmca.pdf.

5. DISCLAIMER; IDENTITY; LIMITATION OF LIABILITY

5.1 Disclaimer. YOU ACKNOWLEDGE AND AGREE THAT THE WEBSITE IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, COMPANY EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. COMPANY DOES NOT WARRANT THAT THE WEBSITE WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS, AND COMPANY MAKES NO WARRANTY REGARDING THE QUALITY, ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF THE WEBSITE.

5.2 Indemnity. By agreeing to this Agreement and using the Website, you agree that you shall defend, indemnify and hold Company, its licensors and their respective parent organizations, subsidiaries, affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including reasonable attorneys' fees and costs) arising out of or in connection with: (a) your use of the Website and any information and/or Content posted on the Website by you or from your account; (b) your violation or breach of any term or condition of this Agreement or any applicable law or regulation; (c) your violation of any rights of any third party; (d) any unauthorized use of the Website; or (e) your negligence or willful misconduct.

5.3 Limitation of Liability. NEITHER COMPANY, ITS SUPPLIERS OR LICENSORS, NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE WEBSITE WILL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT OR FROM THE USE OF OR INABILITY TO USE THE WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT COMPANY HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. THE EXCLUSIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN COMPANY AND YOU.

6. DISPUTE RESOLUTION

6.1 Informal Process First. You agree that in the event of any dispute between you and Company, you will first contact us and make a good faith sustained effort to resolve the dispute before resorting to arbitration under this Agreement.

6.2 Binding Arbitration. Any dispute or claim that remains unresolved after the informal dispute resolution described in Section 6.1, except for disputes relating to the infringement of our intellectual property rights or the access or use of the Website in violation of this Agreement (a “Claim”), will be resolved by binding arbitration, rather than in court, provided that you may assert Claims in small claims court located in New Castle, Delaware if your Claims qualify.

6.3 No Judge or Jury. There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages), and must follow the terms of this Agreement as a court would.

6.4 Arbitrator and Rules. The arbitration will be conducted before a neutral single arbitrator, whose decision will be final and binding, and the arbitral proceedings will be governed by the AAA Commercial Arbitration Rules, Consumer Due Process Protocol, and Supplementary Procedures for Resolution of Consumer Related Disputes. These rules can be found on the AAA website at www.adr.org.

6.5 Starting an Arbitration. To begin an arbitration proceeding, you must send us a notice of dispute, in writing, setting forth your name, address and contact information, the facts of the dispute and relief requested. You must send your notice of legal dispute to us at the following address: contact@lxq.ai. We will send any notice of dispute to you at the contact information we have for you.

6.6 Format of Proceedings. The arbitration will be conducted, at the option of the party seeking relief, by telephone, online, or based solely on written submissions.

6.7 Fees. If you initiate arbitration, your arbitration fees will be limited to the filing fee set forth in the AAA's Consumer Arbitration Rules. Unless the arbitrator finds the arbitration was frivolous or brought for an improper purpose, the Company will pay all other AAA and arbitrator's fees and expenses.

6.8 Individual Basis; Jury Trial Waiver. To the fullest extent permitted by applicable law, you and Company each agree that any proceeding to resolve a Claim will be conducted only in the respective party's individual capacity and not as a plaintiff or class member in any purported class, consolidated, multiple plaintiff or representative action (“Class Action”). If for any reason a Claim proceeds in court rather than in arbitration, you and Company each waive any right to a jury trial. You and Company expressly waive any ability to maintain any Class Action in any forum. If the Claim is subject to arbitration, the arbitrator will not have authority to combine or aggregate similar claims or conduct any Class Action nor make an award to any person or entity not a party to the arbitration. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator.

6.9 Limitation Period. In no event will any Claim or any other action or proceeding by you (including arbitration under this Section 6) be instituted more than one (1) year after the cause of action arose.

6.10 Enforcement. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. The United Nations Conventions on Contracts for the International Sale of Goods will have no applicability.

6.11 Invalidity. If a court of competent jurisdiction finds the foregoing arbitration provisions invalid or inapplicable, you and Company each agree to the exclusive jurisdiction of the Federal and State courts located in Dover, Delaware, and you and Company each agree to submit to the exercise of personal jurisdiction of such courts for the purposes of litigating any applicable dispute or claim.

6.12Opting Out. If you do not want to arbitrate disputes with Company and you are an individual, you may opt out of this arbitration agreement by sending an email to contact@lxq.ai within thirty (30) days of the first of the date you access or use the Service.

7. MISCELLANEOUS

7.1 Assignability. You may not assign this Agreement or any of your rights or obligations hereunder without our prior written consent. Company may freely assign this Agreement. Any attempted assignment or transfer in violation of this Section 7.1 will be null and void. Subject to the foregoing restrictions, this Agreement will inure to the benefit of the successors and permitted assigns of the parties.

7.2 Entire Agreement. This Agreement set forth the entire agreement and understanding of the parties relating to its subject matter and cancels and supersedes any prior or contemporaneous discussions, agreements, representations, warranties, and other communications between them.

7.3 Governing Law. This Agreement and any controversy, dispute or claim arising out of or relating to this Agreement will be governed by and construed in accordance with the laws with the State of Delaware, without regard to its conflict of law provisions.Modifications. We may modify this Agreement at any time. 

7.4 Modifications become effective immediately upon your first access to or use of the Website after the “Last Revised” date at the top of this Agreement. If we make changes that are material, we may use reasonable efforts to attempt to notify you, including by email or placing a prominent notice on the Website. Your continued access or use of the Website after the modifications have become effective will be deemed your conclusive acceptance of the modified Agreement. If you do not agree with the modifications to the Agreement, then please do not access or use the Website.

7.5 Notices; Consent to Electronic Notice. You consent to the use of electronic means to deliver any notices pursuant to this Agreement. Notices will be given: (a) by Website via email (in each case to the email address that you provide when registering your account); (b) via the Website; or (c) by you via email to contact@lxq.ai.

7.6 No Waiver. The failure or delay of Company to exercise or enforce any right or claim does not constitute a waiver of such right or claim and will in no way affect Company’s right to later enforce or exercise it, unless Company issues an express written waiver, signed by a duly authorized representative of each party.

7.7 Severability. If and to the extent any provision of this Agreement is held illegal, invalid, or unenforceable in whole or in part under applicable law by a court of competent jurisdiction, such provision or such portion thereof will be ineffective as to the jurisdiction in which it is illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability, and will be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the parties.

7.8 Contact Us. If you have any questions about this Agreement or the Service, please contact us at LXQ Inc., 8 The Green #19090, Dover, DE, 19901, United States, contact@lxq.ai.`}
        </pre>
      </div>
    );
  }